### ISSUE TITLE
Attach wget friendly libc-musl builds to your releases

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [ken-matsui/jyt#136]
Hello,

would it be possible for you to add statically built libc-musl linux binaries to your release? (I only need amd64)
I am aware that I can install jyt via cargo but when building docker images that should be as small as possible 
installing cargo and rustc is not an option. A libc-musl binary has no dependencies to the system and can always be included in any linux container and it will work. This is the ideal thing for an utility such as yours. To make life easy you could just add this binary to your github releases so I can just wget <link> -> /usr/bin/jyt when building such a docker image.

I know I can easily build this myself, but I would have to do it again for each update, plus it would turn a 1 liner in a dockerfile into about ~20 lines. I am sure I am not the only person that would appreciate this.

PS: The windows guys would probably appreciate a .exe download too.

**Comment by ken-matsui** [comment]
Sure, I can work on that when I get time. I'm not familiar with Windows, so it won't be provided, sorry.

**Comment by ken-matsui** [comment]
Done → https://github.com/ken-matsui/jyt/releases/tag/v0.3.1

Please let me know if the binary is not built correctly or you find anything incorrect.
