### ISSUE TITLE
`CString` should not be freed by the standard C `free()` function

### ISSUE THREAD

**Issue by lizhuohua** [ken-matsui/jyt#16]
Hi, first of all, thanks for your great package.

Here is my nitpick when I read the code. In file `c_api.rs`, the `CString` is deallocated via `free`:

https://github.com/ken-matsui/jyt/blob/1033c8df7d1c35f169ad021312ede45207ca9a45/src/c_api.rs#L120

However, according to the [document of `CSting`](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.into_raw), this is not recommended and is likely to lead to undefined behavior or allocator corruption:

> Specifically, one should _not_ use the standard C free() function to deallocate this string.

Instead, they should be reconstituted using [CString::from_raw](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.from_raw) to be properly deallocated.

**Comment by ken-matsui** [comment]
Hello @lizhuohua,

Thanks for your issue!

I'm not entirely sure I understand C API with Rust, but I suspect that this is not a problem.

> The pointer which this function returns must be returned to Rust and reconstituted using [CString::from_raw](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.from_raw) to be properly deallocated. Specifically, one should not use the standard C `free()` function to deallocate this string.

The sentences mean in the Rust world, we shouldn't use the C `free()` function such as [libc::free](https://docs.rs/libc/latest/i686-unknown-linux-gnu/libc/fn.free.html). However, in the `jyt` case, we want to return a char pointer without accidentally deallocating it by [CString::from_raw](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.from_raw) to delegate the responsibility to caller languages.

This delegation is done by [`mem::forget`](https://doc.rust-lang.org/stable/std/mem/fn.forget.html):

> https://snacky.blog/en/string-ffi-rust.html

https://github.com/ken-matsui/jyt/blob/1033c8df7d1c35f169ad021312ede45207ca9a45/src/c_api.rs#L29

If this C API function is called by C, then the caller has to free the returned pointer manually like `libgit2` does, IMO.

https://github.com/libgit2/libgit2/blob/bdab22384cc61d315005a65456a9f9563bb27c8f/src/libgit2/oid.h#L20

WDYT?

**Comment by lizhuohua** [comment]
What the document recommends is that memory allocated in Rust should also be freed in Rust. One should not allocate memory in Rust and then free it in C.

To my understanding, this is to make sure that memory is allocated and deallocated via the same memory allocator. Because Rust has [the ability to replace the global allocator](https://doc.rust-lang.org/std/alloc/index.html#the-global_allocator-attribute), but the C  `free()` function doesn't. For example, on Linux, users can compile and link Rust code with `jemalloc`, while `free` always uses `ptmalloc` implemented in Glibc.

And of course, if Rust uses the system allcator, it is quite possible that `free()` also works. But it is not guaranteed in the future.

**Comment by ken-matsui** [comment]
Thank you so much for your information!

I certainly misunderstood allocators. I then have to allocate memory on the C side, pass the pointer to Rust, and free the pointer in C. I'm going to fix this problem.

Again, thank you for your issue!
